site_name: APTX4869-CONAN
theme: 
  name: material
  icon:
    logo: material/library
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式

  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - search.suggest
    - search.highlight
  language: zh

nav:
  - 主页: index.md
  - 附页: 
      - Learn c: appendix/c.md
      - 计算机系统基础: appendix/cs.md
      - Makefile: appendix/Makefile.md
      - Linux: appendix/Linux.md
      - 精通工具: appendix/tools.md
      - Tmux: appendix/tmux.md
      - markdown: appendix/markdown.md
      - code: appendix/code.md
      - git: appendix/git.md
      - 快捷键: appendix/key.md
      - 代码记录: appendix/Ccode.md
      - 想法: appendix/idea.md
      - 代码用法: appendix/use.md
  - 解决的问题: bugs.md
  - 其他:
      - makefile: sundries/makefile.md
      - placeholder: sundries/placeholder.md
      - 进制: sundries/1.md
      - char: sundries/2.md
      - 整数大小: sundries/3.md
      - 联合体: sundries/4.md
      - for循环: sundries/5.md
      - 布尔代数式: sundries/6.md
      - 指针: sundries/7.md
      - 字符串指针数组: sundries/8.md
      - ex15: sundries/9.md
      - 结构体: sundries/10.md
      - ex16: sundries/11.md
      - ex17: sundries/12.md
      - 堆和栈的内存分配: sundries/13.md
      - 回调函数: sundries/14.md
      - 预处理: sundries/15.md
      - OOP: sundries/16.md
plugins:
  - mermaid2:
      arguments:
        theme: light

extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
extra:
  homepage: http://aptx4869-conan.github.io/zzp-blog
  social: # icons
#   - icon: fontawesome/brands/bilibili
#     link: https://space.bilibili.com/1436476753
#     name: Bilibili | 浩哈哈哈哈 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/APTX4869-CONAN
      name: GitHub | ZZP(APTX4869-CONAN)
## [bottom-left corner]
copyright: Copyright &copy; 2023-现在 APTX4869-CONAN # 左下角的版权声明
